# ==========================================
# PUERTO DEL SERVIDOR
# ==========================================
server.port=8127

# ==========================================
# CONEXI�N A NEON (PostgreSQL)
# ==========================================
spring.datasource.url=jdbc:postgresql://ep-polished-hall-aik2myb1-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_KvaHclbWL8t5
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA CONFIGURATION
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# THYMELEAF
# ==========================================
spring.thymeleaf.cache=false